### ISSUE TITLE
Consider adding kotlin-stdlib-jdk8

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/kiwi-bom#180]
We already have kotlin-stdlib and kotlin-stdlib-common in the BOM, perhaps we should also add kotlin-stdlib-jdk8 as well.

[The different kotlin-stdlibs explained](https://mbonnin.medium.com/the-different-kotlin-stdlibs-explained-83d7c6bf293) does a good job explaining the differences between these libraries. In my opinion, the official Kotlin documentation for [Gradle](https://kotlinlang.org/docs/gradle.html) or [Maven](https://kotlinlang.org/docs/maven.html) doesn't do as good a job as it should. They actually have a section on Ant, too - does anyone still use Ant?

**Comment by chrisrohr** [comment]
Why would we want/need jdk8 when we are on 11 and 16/17?

**Comment by sleberknight** [comment]
They are extensions to the kotlin-stdlib for Java 8 and above. That Medium blog post does a good job explaining, but the TL;DR is that it adds extensions to Java 8 streams, to Duration, and adds support for ThreadLocalRandom. Per the post:

> kotlin-stdlib-jdk8 adds extension functions to convert from [java.util.Stream](https://docs.oracle.com/javase/8/docs/api/java/util/stream/package-summary.html) to kotlin.sequences.Sequence and kotlin.collections.List [source](https://github.com/JetBrains/kotlin/blob/e3883d8d6ddd609e8c0d2ae9af9ab6fb1059dd36/libraries/stdlib/jdk8/src/kotlin/streams/Streams.kt)

> kotlin-stdlib-jdk8 adds extension functions to convert to/from java.time.Duration and kotlin.time.Duration [source](https://github.com/JetBrains/kotlin/blob/ff9d2744ce9b63321504cb70cf500bb99bc59f75/libraries/stdlib/jdk8/src/kotlin/time/DurationConversions.kt)

> Named groups in regular expressions [Provide access to named groups of regex match result](https://youtrack.jetbrains.com/issue/KT-12753)

> Support for [ThreadLocalRandom](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadLocalRandom.html) - "kotlin-stdlib-jdk8 will default to ThreadLocalRandom for [Random.Default](https://github.com/JetBrains/kotlin/blob/695d657ca88faf42d56917cf60619aaea5035407/libraries/stdlib/src/kotlin/random/Random.kt#L242). This should remove some contention in multi-threaded scenarios..."
