### ISSUE TITLE
Consider adding spring-data-commons dependency

### ISSUE THREAD

**Issue by sleberknight** [kiwiproject/kiwi-bom#181]
Should we add spring-data-common as a separate dependency? It is _possible_ for something to only need that dependency (though perhaps unlikely). Since its version is different than the other spring-data-xxx (i.e. spring-data-mongodb), it might be worth controlling it separately, with the downside that we need to make sure the version matches the one depended on by the other spring-data-xxx libraries.

**Comment by chrisrohr** [comment]
Sure?
